### ISSUE TITLE
Dependency Conflict with sqlglot on MS Fabric Notebook install

### ISSUE THREAD

**Issue by muhammadafayyaz** [mrjsj/msfabricutils#42]
<img width="714" alt="fabric_msfabricutils_install_conflict" src="https://github.com/user-attachments/assets/9000bda2-4c63-4919-a709-a780cc28498e" />

Attached dependency conflict occurs when running a pip install on the msfabricutils library using a default Fabric Python 3.11 notebook.

**Comment by mrjsj** [comment]
Thanks for the report. 😊
